// Places for the schedule's location picker, from the IANA tz database
// (zones.json, generated by scripts/build-geo-data.mjs): each time zone has
// a representative city with coordinates - "Europe/Warsaw" → Warsaw.

import tzlookup from "@photostructure/tz-lookup";
import { locale } from "@/i18n";
import type { ScheduleLocation } from "@/types";
import ZONES from "./zones.json";

export type Zone = { id: string; countries: string[]; lat: number; lon: number };

export const zones: Zone[] = ZONES;

/** "Europe/Kiev" style old names still resolve through Intl to the current one. */
function canonical(timeZone: string): string {
  try {
    return new Intl.DateTimeFormat("en-US", { timeZone }).resolvedOptions().timeZone;
  } catch {
    return timeZone;
  }
}

export function cityName(zoneId: string): string {
  return (zoneId.split("/").at(-1) ?? zoneId).replaceAll("_", " ");
}

const regions = (() => {
  try {
    return new Intl.DisplayNames([locale], { type: "region" });
  } catch {
    return null;
  }
})();

export function countryName(code: string): string {
  return regions?.of(code) ?? code;
}

function placeName(zone: Zone): string {
  const country = zone.countries[0];
  return country ? `${cityName(zone.id)}, ${countryName(country)}` : cityName(zone.id);
}

/** The time zone's city as a location - the default before the user picks one. */
export function zoneLocation(timeZone: string): ScheduleLocation | null {
  const id = canonical(timeZone);
  const zone = zones.find((z) => z.id === id || z.id === timeZone);
  return zone ? { lat: zone.lat, lon: zone.lon, timeZone: zone.id, name: placeName(zone) } : null;
}

/** The time zone at a point (land and sea). */
export function zoneAt(lat: number, lon: number): string {
  try {
    return tzlookup(lat, lon);
  } catch {
    return "Etc/UTC";
  }
}

/** A picked point: its time zone, named after the nearest zone city. */
export function locationAt(lat: number, lon: number): ScheduleLocation {
  const timeZone = zoneAt(lat, lon);
  const city = zones.find((z) => z.id === timeZone);
  return {
    lat: Math.round(lat * 100) / 100,
    lon: Math.round(lon * 100) / 100,
    timeZone,
    name: city ? placeName(city) : timeZone,
  };
}

/** Cities and countries matching `query` ("new york", "poland"). */
export function searchPlaces(query: string, limit = 8): ScheduleLocation[] {
  const q = query.trim().toLowerCase();
  if (q.length < 2) return [];
  return zones
    .filter((z) => placeName(z).toLowerCase().includes(q) || z.id.toLowerCase().includes(q))
    .slice(0, limit)
    .map((z) => ({ lat: z.lat, lon: z.lon, timeZone: z.id, name: placeName(z) }));
}
